// (Copyright) [2019 - 2019] Confluent, Inc.

package io.confluent.security.store.kafka.coordinator;

/**
 * Rebalance listener implemented by the writer manager. Partition writer lock
 * must not be held be the caller when the notification methods are invoked since
 * these methods may acquire one or more partition writer locks.
 */
public interface MetadataServiceRebalanceListener {

  /**
   * Assignment completion notification generated when rebalance completes.
   */
  void onAssigned(MetadataServiceAssignment assignment, int generationId);

  /**
   * Assignment revocation notification generated when rebalance commences.
   */
  void onRevoked(int generationId);

  /**
   * Writer resignation notification generated by the writer when an error
   * is encountered, cache refresh times out or a generation marker with
   * newer generation is is received. This is used to trigger re-election.
   */
  void onWriterResigned(int generationId);
}
