// (Copyright) [2016 - 2016] Confluent, Inc.
package io.confluent.metrics.reporter.integration;

import kafka.server.KafkaConfig;

import java.util.Properties;

import static org.junit.Assert.assertEquals;

/**
 * MetricsReporterTest using auto-generated IDs instead of statically assigned ones.
 * This is a regression test for CP-436 / KAFKA-4756.
 */
public class MetricsReporterTestWithAutoGeneratedIds extends MetricsReporterTest {
    @Override
    protected void injectProperties(Properties props) {
        super.injectProperties(props);
        props.setProperty(KafkaConfig.BrokerIdGenerationEnableProp(), "true");
        props.setProperty(KafkaConfig.BrokerIdProp(), "-1");
    }

    @Override
    protected void verifyBrokerId(int brokerId) {
        assertEquals("brokerId should match", 1002, brokerId);
    }
}
