IMAGE_NAME := ce-trogdor
BASE_IMAGE := confluent-docker.jfrog.io/confluentinc/ce-kafka
BASE_VERSION := latest
RELEASE_BRANCH := ce-trunk
DEFAULT_BUMP := minor

include ./mk-include/cc-begin.mk
include ./mk-include/cc-semver.mk
include ./mk-include/cc-docker.mk
include ./mk-include/cc-end.mk
